version: "3.9"

services:
  redis:
    image: "redislabs/redistimeseries:1.6.0"
    profiles: [ "devel-native", "devel-docker", "prod" ]
    restart: unless-stopped
    ports:
      # redis connection
      - "127.0.0.1:6379:6379"

  telestion-devel:
    image: "telestion-devel"
    profiles: ["devel-docker"]
    build:
      context: "."
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      # passthroughs TCP EventBus Bridge to allow connections from clients on host
      - "127.0.0.1:9870:9870"
    volumes:
      # pass configuration to container
      - type: bind
        source: "./conf"
        target: "/usr/telestion/telestion-project-workshop/conf"

  telestion:
    image: "ghcr.io/wuespace/telestion-project-workshop:latest"
    profiles: ["prod"]
    restart: unless-stopped
    ports:
      # passthroughs TCP EventBus Bridge to allow connections from clients on host
      - "127.0.0.1:9870:9870"
    volumes:
      # pass configuration to container
      - type: bind
        source: "./conf"
        target: "/usr/telestion/telestion-project-workshop/conf"

# rename default docker network
networks:
  default:
    name: telestion-net
